Added Coach's Coin Clicker to the SHDW Ecosystem page
GenesysGo/docs-shadow-cloud pull request #85
Opened 2023-12-13 19:00 UTC by CoachChuckFF

I've added Coach's Coin Clicker to the ecosystem page. It is a nice little perma-app that showcases the power of ShdwDrive's potential for immutable storage.

2023-12-13 19:04 UTC, tracy-codes requested changes

2023-12-13 19:04 UTC, tracy-codes commented on build/shadow-drive/community-maintained-uis.md
> +[![](<../../.gitbook/assets/coach-coin-clicker.png>)](https://shdw-drive.genesysgo.net/81AsEZByxnLFnpXVBLEASxvxknJ5pNWrbXP647iSv6Qh/Screenshot%202023-12-13%20at%2012.39.23%20PM.png)
Instead of a link to the png on shdw drive, can you please have it link out to the app's actual website?

2023-12-15 14:42 UTC, CoachChuckFF commented on build/shadow-drive/community-maintained-uis.md
> +[![](<../../.gitbook/assets/coach-coin-clicker.png>)](https://shdw-drive.genesysgo.net/81AsEZByxnLFnpXVBLEASxvxknJ5pNWrbXP647iSv6Qh/Screenshot%202023-12-13%20at%2012.39.23%20PM.png)
Good catch, thanks!

2023-12-18 18:40 UTC, tracy-codes approved these changes

2023-12-18 18:40 UTC, merged